### ISSUE TITLE
Manifest creation fails

### ISSUE THREAD

**Issue by r4sas** [Noelware/docker-manifest-action#131]
Hello.
Thank you for your workaround with docker containers merging with manifest.

Lately it start fail when trying to create manifest. Example output can be found here: https://github.com/PurpleI2P/i2pd/actions/runs/4001302421/jobs/6867928655

```
/usr/bin/docker manifest create --amend purplei2p/i2pd:latest purplei2p/i2pd:latest-amd64 purplei2p/i2pd:latest-i386 purplei2p/i2pd:latest-arm64 purplei2p/i2pd:latest-armv7
docker.io/purplei2p/i2pd:latest-amd64 is a manifest list
```

How can we fix this?

**Comment by r4sas** [comment]
I can try modify workflow and add `amend: false` manually if needed.

**Comment by auguwu** [comment]
Please do! If it still continues to error, please tell so I can try to find some solutions!

**Comment by auguwu** [comment]
The action actually forces **amend: true** in the `docker manifest create` command and doesn't `amend: true` in `docker manifest push`, I'll need to fix that in a few hours (and maybe you can try again when it is pushed?)

**Comment by r4sas** [comment]
Just tested with `amend: false`, and looks like it is ignored: https://github.com/PurpleI2P/i2pd/actions/runs/4018882640/jobs/6905044176#step:7:5

**Comment by r4sas** [comment]
> The action actually forces **amend: true** in the `docker manifest create` command and doesn't `amend: true` in `docker manifest push`, I'll need to fix that in a few hours (and maybe you can try again when it is pushed?)

Ok, I'm waiting.

**Comment by r4sas** [comment]
https://github.com/Noelware/docker-manifest-action/commit/daf8cd4752cff9aec8e0e84d6cfa323ab06b82f6#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R53

**Comment by auguwu** [comment]
I just got the issue right now: ![](https://noel-is.gay/images/fe1dba6c.png)

I'll need to dive more into this

**Comment by r4sas** [comment]
Not easier for me because `linux/arm64`  amd `linux/armv7` platforms build takes too much time, that's why I build them in separate runner for each platform...

Look at workflow graph to understand: https://github.com/PurpleI2P/i2pd/actions/runs/4001302421

**Comment by r4sas** [comment]
Untill last week everything works this way:
* Workflow build every platform in separate runner
* Uploads them as `latest-<arch>` tag
* When all builders finished one more step started, which creates updated tag `latest`

**Comment by r4sas** [comment]
btw, I think that `docker.io` make some changes which broken everything...

**Comment by r4sas** [comment]
And one more link: https://docs.docker.com/engine/reference/commandline/manifest/#create-and-push-a-manifest-list
Example shows that we must use different containers, not tags. But somehow merging of tags worked earlier? Hm...

**Comment by book000** [comment]
Hello. I have also encountered this problem and have found a tentative solution, which I will share with you.

The solution is to add `provenance: false` to `docker/build-push-action` as follows:

```yaml
      - name: Build and push Docker image
        uses: docker/build-push-action@v3.3.0
        with:
          context: .
          push: true
          platforms: ${{ matrix.platform }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: false
```

Related issues may be found here: https://github.com/docker/build-push-action/issues/771

For specific fixes, see the following Pull requests: https://github.com/tomacheese/twitter-dm-memo/pull/31  
Action log before modification: https://github.com/tomacheese/twitter-dm-memo/actions/runs/4001345210
Action log after modification: https://github.com/tomacheese/twitter-dm-memo/actions/runs/4002014080

**Comment by auguwu** [comment]
Thank you for a solution! I'll add it to the README and keep this issue open (or not? I don't know in this case)

**Comment by r4sas** [comment]
@book000 thank you for solution, I'll try it soon.

@auguwu I have question about options names, I agree with `extra-images -> images` change, but why calling output image tag as `inputs`?

**Comment by r4sas** [comment]
> images
> Comma-seperated list of images that will be applied in the merged manifest from the [inputs](https://github.com/Noelware/docker-manifest-action#inputs).

Isn't `docker manifest create` creates new one manifest? I don't think it applies changes to existing, and can read only one output per execution. Current action code supports execution for each target image in list?

**Comment by book000** [comment]
@r4sas 

> add: One more, `https://github.com/Noelware/docker-manifest-action#inputs` - incorrect warning:
> 
> > `extra-images` has been renamed to `output`

Please see #134 and #136

**Comment by r4sas** [comment]
> Please see #134 and #136

Oops, haven't seen them before, thanks.
In that case, I think this issue can be closed for now.

**Comment by r4sas** [comment]
> The solution is to add `provenance: false` to `docker/build-push-action` as follows:

It works. Thank you again.
