### ISSUE TITLE
[BUG] Error: Module "perf_hooks" was not found. Did you install it?

### ISSUE THREAD

**Issue by BeyerJC** [Noelware/docker-manifest-action#253]
Hey,
when executing the action, the job fails with error 
```
Error: Error: Module "perf_hooks" was not found. Did you install it?
```

I noticed this problem first today when my cron based job (once a week) ran.

**Comment by BeyerJC** [comment]
This projects CI also fails since this run --> https://github.com/Noelware/docker-manifest-action/actions/runs/5563131305/jobs/10161889898

**Comment by auguwu** [comment]
It is an issue with `@noelware/utils`, I am aware and will fix it soon.

**Comment by auguwu** [comment]
New version of `@noelware/utils` has been released, I'll merge the issue when Renovate picks it up and update the source (in `build/`)
